### ISSUE TITLE
Failed compile with Vue-material-3

### ISSUE THREAD

**Issue by NikitaSavc** [mylmz10/vue-material-3#27]
Hello, I have problem. I'm using Vue 3 and i've installed this library. 
I want use mdSwitch and used this code: 

```html
<template>
<MdSwitch />
</template>

<script>
import {MdSwitch} from "vue-material-3";
export default {
    name: "DemoPage",
    components: {
        MdSwitch
    }
}
</script>

<style scoped>

</style>
```
But, I have 32 errors(Oh no...): 
https://gist.github.com/NikitaSavc/3b66bd5593d44ed29dec7049add4b170

**Comment by mylmz10** [comment]
Hello @NikitaSavc, I guess your project does not have sass. You need to install sass and configure it to use this library.

**Comment by NikitaSavc** [comment]
@mylmz10 thank you. I just installed library sass with command: 
`npm i sass`
And it works. 

But add package `sass` in depends of your library.
